import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.user.create.useMutation()
  const currentUser = api.user.isAuthed.useQuery()
  const login = api.user.login.useMutation()
  const logout = api.user.logout.useMutation()
  const updateprofile = api.user.updateProfile.useMutation()
  const post = api.post.new.useMutation()
  const editedPost = api.post.edit.useMutation()
  const deletePost = api.post.delete.useMutation()
  const likePost = api.post.like.useMutation()
  const unlikePost = api.post.unlike.useMutation()
  const getPost = api.post.getPost.useQuery({postid:'clh6c6rbc0007v5pgjn7k3u13'})
  const postComment = api.comment.new.useMutation()
  const editComment = api.comment.edit.useMutation()
  const deleteComment = api.comment.delete.useMutation()
  const likeComment = api.comment.like.useMutation()
  const unlikeComment = api.comment.unlike.useMutation()

  console.log(getPost)

  let boat 
  //console.log(currentUser)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
   
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <button onClick={() => hello.mutate({email:'bonk', password:'bonk'})}>submit</button> 
            <button onClick={() => login.mutate({email:'bonk', password:'bonk'})}>LOGIN</button> 
              <button onClick={() => logout.mutate()}>LOGOUT</button> 
              <button onClick={() => updateprofile.mutate({bio:'bonk2', education:'bonk'})}>profile testa</button> 
             <button onClick={() => post.mutate({title:'bonk', content:'bonkahbonkbonk'})}>BONKPOST</button> 
              <button onClick={() => editedPost.mutate({postid:'clh6c6rbc0007v5pgjn7k3u13', title:'bonk11', content:'return of the bonk', meta:{url:'myurl.co222m'}})}>editbonk</button> 
             <button onClick={() => deletePost.mutate({postid:'clh6c6rbc0007v5pgjn7k3u13'})}>deleteBOnk</button> 
               <button onClick={() => likePost.mutate({postid:'clh6c6rbc0007v5pgjn7k3u13'})}>likePost</button> 
                 <button onClick={() => unlikePost.mutate({postid:'clh6c6rbc0007v5pgjn7k3u13'})}>unlikePost</button> 
                 <button onClick={() => postComment.mutate({title:'commentbonk',content:'commentbonk', postid:'clh6c6rbc0007v5pgjn7k3u13'})}>comment</button> 
                 
                  <button onClick={() => editComment.mutate({commentid:'clh6jclu60001v5ogqxut88xf', title:'bonk11', content:'return of the bonk', meta:{url:'myurl.co222m'}})}>editcomment</button> 
                  <button onClick={() => deleteComment.mutate({commentid:'clh6jclu60001v5ogqxut88xf'})}>deleteBOnk</button> 
               <button onClick={() => likeComment.mutate({commentid:'clh6jclu60001v5ogqxut88xf'})}>likeComment</button> 
                 <button onClick={() => unlikeComment.mutate({commentid:'clh6jclu60001v5ogqxut88xf'})}>unlikeComment</button> 
            </main>
    </>
  );
};

export default Home;
